---
- name: Run New Relic Installer
  shell: NR_INSTALL_SILENT=true newrelic-install install
  notify:
    - Restart PHP-FPM

- name: Restart PHP-FPM
  service: name={{ php_fpm_service }} state=restarted
  ignore_errors: yes
  
