---
- name: Run New Relic Installer
  shell: NR_INSTALL_SILENT=true newrelic-install install
  notify:
    - Remove ini
    - Restart PHP-FPM

- name: Restart PHP-FPM
  service: name={{ newrelic_php_fpm_service }} state=restarted
  ignore_errors: yes

#TODO: dirtry hack. A better approach is needed.
- name: Remove ini
  file:
    path="{{ item }}"
    state="absent"
  with_items:
    - /etc/php/5.6/cli/conf.d/newrelic.ini
    - /etc/php/5.6/fpm/conf.d/newrelic.ini
    - /etc/php/7.0/cli/conf.d/newrelic.ini
    - /etc/php/7.0/fpm/conf.d/newrelic.ini
    - /etc/php/7.1/cli/conf.d/newrelic.ini
    - /etc/php/7.1/fpm/conf.d/newrelic.ini
